AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SNS

Parameters:
  TeamsWebHook:
    Type: String
    Default: ""

Resources:
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "TeamsTopic"

  TeamsForwarderFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: SNS2Teams::SNS2Teams.Function::FunctionHandler
      CodeUri: ./src/SNS2Teams/
      Timeout: 15
      MemorySize: 512
      Runtime: dotnet8
      Architectures:
      - x86_64
      Environment:
        Variables:
          TeamsWebHook: !Ref TeamsWebHook
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref SNSTopic

  MyAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: "DummyAlarm"
      MetricName: "DummyMetric"
      Namespace: "DummyNamespace"
      Statistic: "Average"
      Period: 300
      EvaluationPeriods: 1
      Threshold: 0.0
      ComparisonOperator: "GreaterThanOrEqualToThreshold"
      AlarmActions:
      -  !Ref SNSTopic

Outputs:
  SNSArn:
    Description: SNS ARN
    Value: !Ref SNSTopic